version: "2"

### ONly start the basic services (Kafka, Camunda Optomize) so that all other services can be started manually
services:

  ### Optimize Process Events Monitoring
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-logs:/usr/share/elasticsearch/logs
    restart: always
    mem_limit: 2g

  cambpm:
    image: registry.camunda.cloud/camunda-bpm-platform-ee:7.12.1
    container_name: cambpm
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8080:8080
    restart: always
    mem_limit: 1g

  optimize:
    image: registry.camunda.cloud/optimize:3.0.0-alpha2
    environment:
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://cambpm:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_EVENT_BASED_PROCESSES_ENABLED=true
      - OPTIMIZE_EVENT_BASED_PROCESSES_USER_IDS=['demo']
      - OPTIMIZE_EVENT_INGESTION_ACCESS_TOKEN=mytoken
    container_name: optimize
    ports:
      - 8090:8090
    depends_on:
      - cambpm
      - elasticsearch
    restart: always
    mem_limit: 2g
    volumes:
      - ./OptimizeLicense.txt:/optimize/environment/OptimizeLicense.txt

  #### Kafka
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-kafka:latest"
    hostname: kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

####
volumes:
  elasticsearch-data:
  elasticsearch-logs: